### PR TITLE
Mod Examples

### PR DESCRIPTION
**Pull request by spaar**
Also see #23.
What do you think about these examples? Should we add more, something more advanced maybe? Or will this do for now?

### CODE REVIEW

**Comment by ZiMMy** [comment]
I think it's meaningless to make examples that teach people the Unity documentation.

**Comment by spaar** [comment]
Do you mean the basic skeleton? If so, I mostly made it as a template for people to look at, especially for people who wouldn't otherwise know where to start.

**Comment by ZiMMy** [comment]
I think that basic one is absolutely enough to start (if we assume that modders at least know C#, are able to read Unity documentation, to decompile Assembly-UnityScript and other mods).

**Comment by spaar** [comment]
Ah, so you think the shooter one is unnecessary.
I made it mostly as a simple example for a mod that actually _does_ something instead of just being loaded, but I guess we could leave it out.

**Comment by ZiMMy** [comment]
Yes.
So, are you going to release the 0.2? I think it's ready in the current state.

**Comment by spaar** [comment]
Yeah, I'll revert cf9c402, merge this, write the changelog and then package up the releases.

**Comment by spaar** [comment]
Well then, 0.2 is released. I hope I didn't miss something or screw it up in another way ^^

**Comment by ZiMMy** [comment]
I have a question: in a static class do I have to mark all fields and methods as "static" or this is determined automatically?

**Comment by spaar** [comment]
I think you have to mark them as static.
Btw: do you want to join Slack? It'd be much nicer for these sort of things that aren't really related to any PR/issue we could comment on.

**Comment by ZiMMy** [comment]
Yeah. What company name should I enter?

**Comment by spaar** [comment]
You'll have to send me your email address so I can invite you, instead of signing up on their page. (You can do this on the forums via PM if you don't want to post it here publicly.)

**Comment by ZiMMy** [comment]
sent

**Comment by spaar** [comment]
Sent an invite.

**Pull request merged**
