### PR TITLE
Added help files project (Sandcastle package required)

### PR DESCRIPTION
**Pull request by vissie003**
As said in the discription, you need to install Sandcastle with the VS plugin to make it work

Sandcastle:
http://shfb.codeplex.com/

### CODE REVIEW

**Comment by spaar** [comment]
Hmm... the generated help doesn't seem to actually extract the documentation for me.
I just get a red messages, like `[Missing <summary> documentation for "T:spaar.Commands"]` in the HTML output, even though there are clearly documentation comments in the code.
Any idea why?

**Comment by vissie003** [comment]
fixed it, now it still gives that error, but that is because those comments are missing for reall

**Comment by vissie003** [comment]
I am working on a mod that requires a Web API, we might be able to host the documentation along side it...

**Comment by spaar** [comment]
Looks good now. We'll still need to create some more content for that documentation but that's another topic :)
Regarding hosting it, that might be an option or we could host it here using GitHub pages. For now, I'll merge this and get to work creating some more documentation.

**Pull request merged**
